services:
  lispywebc:
    build:
      context: "./Challenges/misc/lispyDev/"
    ports:
      - "8000:4000"
  jwt_john:
    build:
      context: "./Challenges/misc/jwtJohn/"
    ports:
      - "8001:3000"  
  my-first-overflow:
    build:
      context: "./Challenges/reversing/c-is-easy-and-secure/"
    ports:
      - "8002:1337"
  the_unzipper:
    build:
      context: "./Challenges/web/the_unzipper/"
    ports:
      - "8004:1337"
  calculator:
    build:
      context: "./Challenges/web/calculator/"
    ports:
      - "8006:4001"
  command_inject_one:
    build:
      context: "./Challenges/web/commandInjection/challenge1"
    ports:
      - "8007:5000"
  command_inject_two:
    build:
      context: "./Challenges/web/commandInjection/challenge2"
    ports:
      - "8008:5000"
  ciseasyandsecuretwo:
    build:
      context: "./Challenges/reversing/c-is-easy-and-secure-2/"
    ports:
      - "8010:1337"
