FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY robots.txt /usr/share/nginx/html/
COPY eb7b7aae-cc9c-49fd-8133-211a3e44719e/ /usr/share/nginx/html/eb7b7aae-cc9c-49fd-8133-211a3e44719e/

COPY default.conf /etc/nginx/conf.d/default.conf

